# Generated by Django 5.0.6 on 2024-06-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='department',
            new_name='department_id',
        ),
    ]
