# Generated by Django 5.0.6 on 2024-06-05 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='iname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.item'),
        ),
    ]
